### ISSUE TITLE
Slave mode stuck bug

### ISSUE THREAD

**Issue by MagCat** [Masuzu/ZooeyBot#87] opened 2017-06-02 18:09 UTC
I've been fighting this problem for a while now. I have 2 bugs currently going on. The first thing is having devtool docked at bottom. After calibrating the bot keeps either clicking My Page on my main window. I did look at other threads that related to this issue and I tried:

1) No viramate. This solves nothing
2) Switch slave and main window position. Doesn't help
3) Main account not click ready. No my main never clicks on ready, since the bot KEEPS directing to home page for whatever the reason instead of starting the quest.

So, I changed the devtool dock position to right instead. Now the bot actually starts the battle, but the bot keeps copy paste the battle url and refresh instead of starting the combat. In short, it does nothing but refresh the page. I tried:
1) Switch slave and main window position. Still refreshing.
2) No viramate (setting ini to false). Still same problem.

**Comment by Masuzu** [comment] 2017-06-02 20:38
Hello,

As for your first issue it is not a bug. Please check the parameter `ChromeDevToolsWindowDockedOnTheRight`.

As for the second issue, when does the refresh happen? Is it after the battle ends and when the bot sets again the quest?
The new version 1.9.0 should wait with an increasing delay between each page refresh should this happen.

**Comment by MagCat** [comment] 2017-06-02 20:48
Hey there,
I did check the parameter. I told you what would happen if I dock DevTools to the right (in that case, parameter set to true instead of false). If that is the way it's intended, then okay. As for when the second issue happens, it was right at the start of the battle, the bot did absolutely nothing to start the combat except to refresh the page. I waited for 5-10 minutes and it still did that. I checked if there was something wrong with lua script or the script link, but no. The script only contains 2 lines of command but the bot executed not even one of them.

character_1:UseSkill(2)
character_2:UseSkill(2)

**Comment by MagCat** [comment] 2017-06-02 23:09
Update with version 1.9.0, the problem still persists and my party still does nothing. I noticed that this time after switching window position, the bot only kept refreshing Slave account page. Turning viramate support on and off in .ini does not change anything either.

**Comment by Masuzu** [comment] 2017-06-03 12:06
Thank you for the feedback and I am glad to hear that it solved the issue.
The problem occurs for people who take "too much" time to reload their page (due to connection quality or computer specs).
I will provide a fix for this to make the "wait time" before refreshing the page configurable in v1.9.2

**Closed** 2017-06-03 12:19 UTC
