### ISSUE TITLE
is double summon supported?

### ISSUE THREAD

**Issue by zannettsama** [Masuzu/ZooeyBot#508] opened 2018-01-18 03:02 UTC
Not sure if user error or has to do with the bot but when I try to summon twice a la lyria it doesn't seem to work?

**Comment by rebokz** [comment] 2018-01-18 04:21
it should if you write the lua script correctly, depending on what turn you want to use the second summon just make sure you write 

If Turn == 1 Then
-- [ [Use the support summon on the first turn--] ]
Summon (6) 

then make another one that uses the second summon in what ever position it is in

**Comment by zannettsama** [comment] 2018-01-18 04:43
@rebokz 
If I wasn't clear, I'm trying to use lyria's gimmick of two summons in the same turn. But uh no so far doesn't work for me.

**Comment by rebokz** [comment] 2018-01-18 06:07
i just figured if you wrote a lua script to use two summons on the same turn then it should work with no problem, im not entirely sure how lyria works cus i've never used her and dont have her but i figured if you wrote two scripts for using a summon on X turn then i figured it would work

**Comment by rebokz** [comment] 2018-01-18 07:51
nevermind see - https://github.com/Masuzu/ZooeyBot/issues/398 Lyria is not yet supported

**Comment by Masuzu** [comment] 2018-01-18 09:00
Hello,
Thank you for reaching out.
This is a duplicate of #398 indeed.

**Closed** 2018-01-18 09:00 UTC
