### ISSUE TITLE
Summoning loop using trial battle

### ISSUE THREAD

**Issue by Jormungands** [Masuzu/ZooeyBot#755] opened 2018-04-23 06:00 UTC
Hi.
If you use the ZooeyBot to do a guild war, you will use a trial battle if you do not see the summon stone you specified, but because you will switch to the summon stone selection screen without withdrawing the trial battle, resetting the summoned stone I will end up looping the trial battle and summon stone selection screen endlessly.
Only when the above symptoms are occurring, a warning "1 warnings" appears at the upper right of DevTools, but is it related to symptoms?
When opening the console, "[Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated due to its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/."

By using the prediction service in Chrome settings you are typing in the address bar and completing the search is supposed to turn off.
After that I attempted to delete the history, but the result did not change.Thanks.

![gran0423](https://user-images.githubusercontent.com/31189131/39109209-d3acd130-4706-11e8-9c5e-542ca50ee6ee.png)

**Comment by Masuzu** [comment] 2018-04-23 07:47
Hello,
The case you are describing is due to a failure to retreat from the trial battle, for some reason. However rare it is, this shows that could still happen.
After entering the trial battle, Zooey will navigate to the Quest menu to retreat.

**Comment by calvinhyang** [comment] 2018-04-23 08:55
Happening to me too when farming GW. IT's not going to the quest page to retreat, it's just going straight to the link for picking a Summon for EX+ and gets stuck in infite loop from going back into same trial battle and summon pick

**Comment by Nassy1121** [comment] 2018-04-23 12:18
Me too.
This issue is also faced in Sarasabot.
For the work around, I close Zooeybot and need to restart.
[log.zip](https://github.com/Masuzu/ZooeyBot/files/1938089/log.zip)

**Comment by ZoiUser** [comment] 2018-04-23 13:13
Hitting into the same issue too. It works sometimes when I monitor it but in the end it gets stuck in this loop where it cant retreat from trial and keeps trying to find a suitable summon. Any ETA fix for this? Been having trial reset issues for a while even in past versions

**Comment by shadowfinted** [comment] 2018-04-24 03:43
same here having the same issue. it cant retreat from trial battles.

**Comment by Jankos5571** [comment] 2018-04-24 06:27
I get this issue everytime the bots attempts to retreat from trial battle. This is not a rare occurrence. The fix that you stated a month ago that would potentially fix this issue was never implemented into the bot either,

**Comment by Poko302** [comment] 2018-04-25 01:47
This happnned to me too during farming GW EX+. It happenned almost every time when it tried to reroll.

**Comment by Masuzu** [comment] 2018-04-25 18:34
Hello,

> it does not go to the quest page to have the option to retreat

I can't even reproduce this part for now !? >_<

**Comment by Masuzu** [comment] 2018-04-25 19:02
I have just made some amendments in v2.12.1.
You can use this configuration to test summon rerolling:
```
[General]
# Possible values: jp, en. Default to en when the string is malformed. Please make sure that your configuration file is encoded using UTF8 if you use non Unicode characters.
Language=en
# ChromeDevToolsWindowDockedOnTheRight should be set to false if your Chrome DevTools console is docked on the bottom (as seen here https://i.imgur.com/bvTOq0g.png), and to true if it is docked on the right
ChromeDevToolsWindowDockedOnTheRight=false
MaxPageLoadDelayInMsBeforeRetry=3500
# Maximum amount of time Zooey will wait for an expected event to occur (for instance, the attack button appearance) before triggering the fallback policy.
MaxTriggerDelayInMsBeforeFallback=5000
# Maximum delay before an action is deemed to have failed due to a lack of response from the GBF servers
MaxResponseDelayInMs=2000
# Maximum number of retry attempts when an action fails (due to a lack of response for instance) before the fallback policy kicks in
MaxNumActionRetries=2
MinWaitTimeInMsAfterRefresh=1600
# The bot will stop after the given parameter no matter what.
TimeLimitInSeconds=100000
UseViramate=true
# Zooey-bot will stop after using the given number of 1/2 AP potions (resets each time you restart Zooey-bot)
MaxNumPotionsToUse=9999
# Zooey-bot will start using full elixirs when this parameter is set to true if there is no 1/2 AP potions left. In any case, no more than MaxNumPotionsToUse potions will be used
UseFullElixirsWhenNoRemainingHalfAPPotions=false

# Set this parameter to true to use full elixirs instead of half AP potions in priority
UseFullElixirsFirst=false

# Horizontal position of the countdown timer which appears when a nightmare mode is available, with regards to the top left corner of your desktop. No countdown timer is displayed when the Event mode is activated.
CountdownTimerHorizontalPosition=0
# Vertical position of the countdown timer which appears when a nightmare mode is available, with regards to the top left corner of your desktop. No countdown timer is displayed when the Event mode is activated.
CountdownTimerVerticalPosition=0

# The "slave mode" is used to host Co-Op quests (the slime H2-1 stage for instance) using 2 accounts on a same computer.
# It requires the use of 2 accounts and the "zooey-bot-slave" Chrome extension installed in addition to the "zooey-bot" Chrome extension.
# The "slave account" will host the quests and pay the AP cost.
# You can log into a second account on a same computer using Chrome Incognito mode.
# To use this mode, set the parameter Active to true and follow the console instructions.
[SlaveMode]
Active=false
# Relative path to the script to use to customize the behaviour of the main account.
# If left blank, the slave account will attack at each turn.
MainAccountLuaScript=Scripts/demo.lua
# Relative path to the script to use to customize the behaviour of the slave account.
# If left blank, the slave account will attack at each turn.
SlaveLuaScript=Scripts/do_nothing.lua
# By default, Zooey will make the slave account attack first. Set this parameter to true if you would like your main account to attack first.
ProcessMainAccountTurnFirst=false

[Inputs]
DelayInMsBetweenMouseDownAndUp=40
RandomDelayInMsBetweenMouseDownAndUp=20
MouseSpeed=580
MouseScrollSpeed=250
# The bot will stop when you press the given key. The default key is F1. Please refer to https://msdn.microsoft.com/en-us/library/windows/desktop/dd375731(v=vs.85).aspx (the values on this page are given in hexadecimal base).
# If you also use Viramate, DO NOT use a key which is shared by Viramate shortcuts.
ExitKeyCode=112
# After the bot moves the cursor to the target position, wait for the given duration before performing the click
WaitTimeInMsBeforeClickInput=50

[PartySelection]
# Integer which defines the party group to use. If an integer outside of the range [1, 7] (boundaries included) is provided, the current party group will be selected.
PreferredPartyGroup=4
# Integer which defines the party deck to use. If an integer outside of the range [1, 6] (boundaries included) is provided, the current party deck will be selected.
PreferredPartyDeck=2
# Integer which defines the party group to use for the nightmare mode. If an integer outside of the range [1, 7] (boundaries included) is provided, the current party group will be selected.
PreferredNightmareModePartyGroup=0
# Integer which defines the party deck to use for the nightmare mode. If an integer outside of the range [1, 6] (boundaries included) is provided, the current party deck will be selected.
PreferredNightmareModePartyDeck=0
# Relative path to the Lua script to use to select programmatically a party based on the selected support summon
PartySelectionScript=party_selection.lua

[Summons]
# Comma-delimited list of summons which will be selected in priority if they are available
PreferredSummons=FooBar
# In case none of the preferred summons was found, select a random summon in the given summon attribute tab, unless the parameter RerollSummonWhenNoPreferredSummonWasFound is set to true.
# Possible values are 'misc' (Kaguya, White Rabbit fall into this category), 'fire', 'water', 'earth', 'wind', 'light' or 'dark'.
# Not case-sensitive.
DefaultSummonAttributeTab=Light
# Zooey will reroll summons until one of the preferred summons is available, using trial battles to refresh the summon list. This does not apply to the summon selection for the nightmare stage (see the EventMode section).
RerollSummonWhenNoPreferredSummonWasFound=true
```
The summon to reroll being non-existent, it'll keep rerolling it.

**Comment by calvinhyang** [comment] 2018-04-26 03:43
Something that I noticed is that it only happens for me when farming Ex+ GW. It hasn't happened to me while farming nm90 yet. Might just be coincidence, and the fact that farming Ex+ is just much faster in general, so there are more chances for the error to happen.

**Comment by Masuzu** [comment] 2018-04-26 19:37
What I can say is that the bot won't go back to the trial battle if a message saying that the retreat button could not be found is displayed with the latest version.

**Closed** 2018-05-09 18:02 UTC
