### ISSUE TITLE
zooey can't use skill popup and Summon popup short cut key

### ISSUE THREAD

**Issue by matp07289** [Masuzu/ZooeyBot#1008] opened 2019-01-18 00:52 UTC

**Comment by falassiry** [comment] 2019-01-18 00:58
It's related to a Viramate update that just got released. Keyboard shortcut functionality slightly changed and 1click summon has been temporarily disabled.

**Comment by Miyoumu** [comment] 2019-01-18 01:08
Can confirm Viramate is the cause.

**Comment by matp07289** [comment] 2019-01-18 01:10
already viramate downgrade for 1.7.1 but can't use viramate

**Comment by elp-l** [comment] 2019-01-20 00:53
Viramate developer in reference to 1Q skill shortcut and 5Q-5T shortcuts being disabled: "Not a bug, both are due to a game change. No fix any time soon."

This may need to be addressed on Zooey's side, as "UseViramate" option is non-functional if a script includes summon calls or first character/first slot skill.

**Comment by Masuzu** [comment] 2019-01-21 20:00
Hello,
As @elp-l said, that is an unfortunate regression in Viramate, for now.
I will provide a workaround to still work with Viramate shortcuts enabled, but hopefully Viramate gets updated soon enough.

**Comment by Masuzu** [comment] 2019-01-21 20:47
This is addressed in v3.5.0.

**Closed by Masuzu** 2019-01-21 20:47 UTC
