### ISSUE TITLE
picking misc summons bug (POS 9 and 10 ONLY)

### ISSUE THREAD

**Issue by LordShade** [Masuzu/ZooeyBot#293] opened 2017-09-20 04:05 UTC
This is referencing an earlier issue you closed @Masuzu 

A lot earlier I reported that Zoey has issue picking summons that are far down the list in the misc category, however, I was told to fix the issue I would have to edit the MouseScrollSpeed variable to a lower number.

However, after mucking around with this value over 20 times, including setting it to a value of 10 (when its default is like 350) Zoey will constantly, screw up on summons that are in Position 9 and 10. I've had several failed raid schedules screwed up by a single person having their Bahamut or Lucifer show up in slot 9 or 10 and halting the entire process (requiring me to setup a second lua script to continue where it left off)

A small option to disable the misc category for summon picking would work out as a quick fix however, I feel this is actually a bug because it's happening on a near daily basis for me no matter what. The only time I can stop it happening is if I 

- get really lucky with summons showing up only in their respected category

- have alot of friends that carry the summon I want in the correct category, sadly for Bahamut I do not have many so Zoey will almost constantly go to the misc category to pick somebody who has placed one there. And seeing as how the first 8 slots are reserved for your friends (2x each) it screws up. Most people would put a Bahamut in the dark category but there a few (lucky lil shits) who run Hades in dark and Baha as misc support.

Picture : https://puu.sh/xE83g/2c8593c180.png

also suggestion, however about a failsafe option if zoey fails 3 times to select a summon like in the picture above?  If it fails to select the summon 3 times she looks for the other summons you have listed? for example I have Bahamut and Celeste Omega as summons to look for, however Zoey will constantly only look for Bahamut and will only pick Celeste Omega if no Bahamut is present (in all categories) If even one is present she forgoes any Celeste Omegas present. However if she cannot locate the Bahamut after 3 attempts (refreshes) she will stop and immediately pick the nearest Celeste Omega to avoid stalling herself.

**Comment by Masuzu** [comment] 2017-09-20 08:52
Hi,

The error showed in the picture is caused by lag issues: if the party selection popup does not show up before `MaxResponseTime` (configuration parameter in the ZooeyBot.ini file), then this is what will happen. Even with a 300 ms ping on my side I never run into this issue (unless during rare occasions which were caused by my ISP...).

On my side, in several occasions Zooey picks summons at the bottom of the list, and so far it never failed me. However, some mitigations might be considered in a later fix. This seems similar to https://github.com/Masuzu/ZooeyBot/issues/287

**Comment by LordShade** [comment] 2017-09-20 09:57
definitely not the case, Zoey is hitting misc summon, scrolling to a certain point, and is bugging out immediately. It seems to always be either position 9 or 10. Both Positions fall just after friend reserved summons and the point Zoey scrolls to is too far down, no matter what I do with MouseScrollSpeed does not change this fact, it is not adjusting at all.

Fun fact, if I'm fast enough, I can scroll up and select the problem bahamut/lucifer summon and Zoey will continue as normal!! However I need to select the summon before she engages in the refresh lock. Very annoying. However I will increase Zoey's wait time so I can at least fix the issue if it pops up. Giving me time to select the problem summon and getting it out of summon pool.

This is a very hard thing to replicate, primarily due to its very specific requirements.

**Comment by Masuzu** [comment] 2017-09-20 11:59
Oh, so the issue is caused by scrolling down too far, resulting in Zooey clicking on an incorrect position, which in turns triggers the fallback (summon page refresh after MaxResponseDelayInMs without any party selection popup displayed)?

So far, I only encountered a scrolling issue once when using the treasure event raid mode, in which Zooey would scroll too far. This was fixed by adding a delay of `WaitTimeInMsAfterMouseScroll` after each scroll down increment. This system is not yet available for the summon selection, but it could solve the issue.
I never ran into any similar issue during summon selection in dozens of hours so far.
Thank you for reporting this issue.

**Comment by Masuzu** [comment] 2017-09-23 17:55
Mitigation provided in last release.

**Closed** 2017-09-23 17:55 UTC
Labels: bug

**Comment by lyhonlam** [comment] 2017-11-02 11:01
Reopen this thread.
I can't find a way to get around this issue, always get stuck whenever the summons at lowest positions. Especially at misc page when it try to get Belle Sylphid.

**Comment by LordShade** [comment] 2017-11-02 12:46
#339

already reported it again here
