### ISSUE TITLE
RetrieveStatusEffects does not work in GW

### ISSUE THREAD

**Issue by yuayumia** [Masuzu/ZooeyBot#307] opened 2017-09-23 02:31 UTC
It seems that the setting of RetrieveStatusEffects=true in multi-battle of GW does not become effective.
(Regardless of GW, there is a possibility that the status effect can not be read with multi-battle.)

**Comment by Masuzu** [comment] 2017-09-23 09:48
Could you please provide evidence that it does not work?

**Comment by yuayumia** [comment] 2017-09-23 10:18
Do you get evidence with the following items?

Single battle (It is operating normally)
EventRaidUrl=http://game.granbluefantasy.jp/#event/teamraid033/supporter/722111/3
![ok](https://user-images.githubusercontent.com/31353164/30772201-b0f73a8e-a091-11e7-8305-a325d7bc1556.png)

multi battle
EventRaidUrl=http://game.granbluefantasy.jp/#event/teamraid033/supporter/722151/1
![ng](https://user-images.githubusercontent.com/31353164/30772202-b0f97cf4-a091-11e7-87c6-8955946b819c.png)

The time stamp of status_effects.txt has been updated. But it is 0 kb.

ZooeyBot.ini used the following items.
[ZooeyBot.ini.txt](https://github.com/Masuzu/ZooeyBot/files/1326452/ZooeyBot.ini.txt)

Thanks.

**Comment by Masuzu** [comment] 2017-09-23 10:21
Ah I see, thank you for reporting the issue.
I found out the cause problem and will try to release a fix as soon as possible.

**Comment by Masuzu** [comment] 2017-09-24 21:02
This should now be fixed in version 1.22.1
https://poker-bot.azurewebsites.net/ZooeyBot/en/Home/PatchNotes#1-22-1

**Closed by Masuzu** 2017-09-24 21:02 UTC
Labels: bug
