### ISSUE TITLE
Bot gets stuck when trying to reroll summons

### ISSUE THREAD

**Issue by DarkenShade** [Masuzu/ZooeyBot#686] opened 2018-03-21 08:50 UTC
the bot gets stuck in training mode when it trys to reroll summons.
it spam refreshes till i turn off the bot.

**Comment by YumeHaru** [comment] 2018-03-22 19:21
It also happens to me from time to time.

**Comment by Masuzu** [comment] 2018-03-24 16:35
Duplicate of https://github.com/Masuzu/ZooeyBot/issues/698

**Closed by Masuzu** 2018-03-24 16:35 UTC
