### ISSUE TITLE
Coop Sliming - Zooey waited a long time before attacking.

### ISSUE THREAD

**Issue by rockysilver** [Masuzu/ZooeyBot#236] opened 2017-08-28 03:21 UTC
I am using the newest version, using auto sliming everything is running fine, except when I go into battle, after the battle is loaded, Zooey waited like 10 seconds before attacking in slave accounts, then another 10 seconds before before attacking with the main account. 

I tried older version 1.8.1 with the same ini file, and it is working fine without the delay, unfortunately that version has the old refresh bug so I can't even use that.

My ini file. 
[ZooeyBot.txt](https://github.com/Masuzu/ZooeyBot/files/1255024/ZooeyBot.txt)

**Comment by Masuzu** [comment] 2017-08-29 11:12
Hi,
Could you please also post here the party compositions and scripts you used too so I can try to reproduce the issue in the same conditions?
Maybe it is completely unrelated, but I will just leave this here https://github.com/Masuzu/ZooeyBot/issues/203

**Comment by rockysilver** [comment] 2017-08-30 05:37
Here is the script I used for slave:
`Summon(6)
SkipAttack()`

The scripts for master is just a blank lua file, I tried with no file, didn't make a difference. 

Master Party: HE MC, Yodarha, Melissabelle, Korwa. Sub: Mahira, Razia
Slave Party: MC, SS Izmir, Lily, SS Charlotta, SS Korwa, SS Beatrix

I slime with 100% ougi.

**Comment by Masuzu** [comment] 2017-08-30 19:12
Thank you, I will test it.

**Comment by Masuzu** [comment] 2017-08-30 19:34
Ah, I got it. The workaround for this issue is very silly: please reduce the value for the parameter `MouseSpeed` to 600 or less, for now, while I add a fix for the long wait time after the message saying "Waiting for Attack button" to be active appears.

**Comment by Masuzu** [comment] 2017-08-30 20:51
Good news, the issue was caused by the newly introduced parameter `RetrieveStatusEffects`. I will fix this as soon as possible. Thank you very much for reporting this bug and I apologize for the inconvenience.

**Comment by Masuzu** [comment] 2017-08-30 20:53
Please just add `RetrieveStatusEffects=false` in the combat section for now and you will be good to go!

**Comment by Masuzu** [comment] 2017-08-30 21:17
This is now fixed in version 1.18.6 https://poker-bot.azurewebsites.net/ZooeyBot/en/Home/PatchNotes#1-18-6

**Closed by Masuzu** 2017-08-30 21:17 UTC
Labels: bug

**Comment by rockysilver** [comment] 2017-09-01 02:04
Thanks for the quick fix!
