### ISSUE TITLE
Party Switching not work first attempt

### ISSUE THREAD

**Issue by ariaanaa** [Masuzu/ZooeyBot#110] opened 2017-06-15 06:54 UTC
so for the first attempt, zoi cant switch the party for the deck but can switch for the group
but the second try it can switch the deck with the number list 

example, i use party group 6 and 6 deck for angel halo farming, but for first attempt zoi just switch the group only not include the deck, and then after finish the first one for the second run it can switch both the group and deck

![image](https://user-images.githubusercontent.com/28663376/27169027-1275c670-51e3-11e7-9a7f-e624157d442e.png)

**Comment by ariaanaa** [comment] 2017-06-15 08:07
edit: solved it by using same party group work fine

**Comment by Dreamfinal** [comment] 2017-06-15 09:34
confirm this bug

If there are different groups. The program will not pick the team.

Now, the problem is with both teams. Stay the same group The program will work normally.

**Comment by Masuzu** [comment] 2017-06-25 20:08
Ah I see what the issue is. Thank you for reporting this.
I will fix it after the guild wars ends.

**Comment by Masuzu** [comment] 2017-06-30 20:04
Fixed in v1.12.0
https://poker-bot.azurewebsites.net/ZooeyBot/en/Home/PatchNotes

**Closed by Masuzu** 2017-06-30 20:04 UTC
Labels: bug
