### ISSUE TITLE
Failed to parse ability - Houndog change skill

### ISSUE THREAD

**Issue by Karbie** [Masuzu/ZooeyBot#340] opened 2017-10-02 03:53 UTC
Hello,
I've having some issue on the bot after changing to 2.0.0
I tried my reown farming script with only the MC using Change skill and Ougi but Zooey would failed to parse ability after MC used its skill.

![issue](https://user-images.githubusercontent.com/25868014/31063731-370aa5ac-a768-11e7-9610-bafd4ade204e.jpg)

**Comment by Masuzu** [comment] 2017-10-02 13:01
Hello,

It seems related to https://github.com/Masuzu/ZooeyBot/issues/335
Could you please provide the ability you are using on your MC so I have more test data to try and reproduce the issue?

**Comment by Karbie** [comment] 2017-10-02 14:20
Hi Masuzu,

I'm using Change on my MC.

![image](https://user-images.githubusercontent.com/25868014/31081905-eca776e0-a7bf-11e7-9a38-60c68e8565eb.png)

**Comment by Masuzu** [comment] 2017-10-02 14:26
Ok, I see, thank you. I will look into it later in the day.

**Comment by Masuzu** [comment] 2017-10-02 18:21
Good news, actually the cause of this bug was different from the one reported in the linked ticket. I will release a patch within 24 hours from now.

**Comment by Masuzu** [comment] 2017-10-02 19:17
Fixed in v2.0.1
https://poker-bot.azurewebsites.net/ZooeyBot/en/Home/PatchNotes#2-0-1

**Closed by Masuzu** 2017-10-02 19:17 UTC

**Comment by Masuzu** [comment] 2017-10-02 19:18
By the way, if you got a "Failed to parse Ability result" it means that you were probably lagging a lot.
This would result in a crash in v2.0.0 but not anymore.
