### ISSUE TITLE
Stuck on calibration?

### ISSUE THREAD

**Issue by Kasenff** [Masuzu/ZooeyBot#37] opened 2017-05-12 06:52 UTC
I am going to the quest screen and it just stays on calibrating now sure how long its supposed to take, I have let it sit for about 10 minutes and nothing is changing. I have everything up to date as well. 

Help?

**Comment by Sarasena** [comment] 2017-05-12 07:33
I have the same problem over here too and it got closed before it was discussed more indepth: https://github.com/Masuzu/ZooeyBot/issues/34

**Comment by MagCat** [comment] 2017-05-12 07:47
Don't enable Viramate option in .ini, it's bugged. When it calibrates, either go to Home Page then go back to Quest Page to update (or refresh Quest Page).

**Comment by Sarasena** [comment] 2017-05-12 08:21
I find that even with that set to false, it isn't the cause either. I took a video to show the problem. The only way for me to fix it is to restart chrome every single time I close Zooeybot just for it to work.

In this video, I just opened a new Google Chrome session and restarted Zooeybot for good measure. You can see that it works fine. However, once I close it and reopen, it gets stuck on Calibration. This is the 100% way for me to replicate this issue. 

If I play GBF for a while before deciding to go bot mode, I will get eternal Calibration problem even without executing it first.

https://youtu.be/q5yIMNjiD3c

**Comment by Masuzu** [comment] 2017-05-12 13:36
@Kasenff 
Please see https://github.com/Masuzu/ZooeyBot/issues/34

@Sarasena In the last video, there is no issue. The calibration won't work unless during the initialization, all the "3 steps" are passed (in your video on the second run, you only reach the initialization step 2/3).
In this case the solution is easy:
Just close the Chrome DevTools window (press F12) before restarting the bot, then reopen it.

**Closed by Masuzu** 2017-05-12 13:36 UTC

**Comment by Masuzu** [comment] 2017-05-12 13:44
@MagCat The Viramate option is not related to the calibration though.
I have been using it from the start (to use Viramate skill shorcuts).
