### ISSUE TITLE
Issue with slave mode in 1.2.0 when the slave page takes longer to load than the main account page

### ISSUE THREAD

**Issue by Nanaya8** [Masuzu/ZooeyBot#28] opened 2017-05-10 17:16 UTC
Sometimes the slave account won't wait for the raid to load and during the "ready" phase it will try to return to the room. By doing that the raid just refreshes, the lua script won't even start and the bot will just stop there. I don't have this problem with the old version of the bot (1.1.010).

**Comment by Nanaya8** [comment] 2017-05-11 11:16
Anyone? it's a pretty annoying bug.  Apparently it just won't wait for the attack button to appear, skips the lua scripts and tries to return to the lobby right away. This is the log:
http://i.imgur.com/l2tVdVq.jpg

**Comment by Kentiah** [comment] 2017-05-11 21:16
I've had this issue when I had a large amount of bandwidth being taken (downloading games/updating games on steam). I assume this has something to do with the 1.2 change "In the slave mode, Zooey will now refresh the result page if the former is stuck loading." and it maybe taking longer to load. Perhaps his normal load time is longer than a normal persons? Some way to change how long the bot considers too long could help if that's the issue, and it's not already MaxPageLoadDelayInMsBeforeRetry.

**Comment by Masuzu** [comment] 2017-05-12 06:18
Hello,

I ran into that issue on my side yesterday and updated the title with the cause of issue.
Will fix this week-end.

**Comment by Masuzu** [comment] 2017-05-12 18:37
This should be fixed in version 1.3.0: https://poker-bot.azurewebsites.net/ZooeyBot/en/Home/PatchNotes

**Comment by Nanaya8** [comment] 2017-05-12 20:37
Thank you!

**Closed** 2017-05-14 09:32 UTC
Labels: bug
