### ISSUE TITLE
"Something went wrong trying to select a summon" looping [Xeno Diablo]

### ISSUE THREAD

**Issue by KuroShiro39** [Masuzu/ZooeyBot#446] opened 2017-12-21 09:07 UTC
Hi admin! I've seen through the previous looping threads and tried to turn off predictive text on chrome or an incognito window but it doesn't seem to work. How can I fix this? I've attached my current settings as a text file for reference.

![bug](https://user-images.githubusercontent.com/34737156/34248352-b1af752a-e670-11e7-9e39-572aa8a24698.jpg)

[ZooeyBot.txt](https://github.com/Masuzu/ZooeyBot/files/1578557/ZooeyBot.txt)

**Comment by agesa** [comment] 2017-12-21 09:21
It started happening right when the UI/content update occurred 20 minutes ago, as far as I can tell.

**Comment by Masuzu** [comment] 2017-12-21 09:24
Hi,
I can't say what the reason is for now. Does Zooey scroll down and click on the summon in your case?
If yes then you are lagging a lot.
If not I will look into it. It may be caused by the update.

**Comment by KuroShiro39** [comment] 2017-12-21 09:28
Yes, it scrolls down to look for the summon.
However, it clicks on the summon and does not click the OK prompt to start the raid and reloads the page and then loop. (XenoDiabloEX in my case)

**Comment by agesa** [comment] 2017-12-21 09:31
The mouse remains hovered over the summon after clicking it and the party confirmation screen appears.  After a few seconds, that error appears.  I've only checked this with Xeno Diablo ex as of right now though, will check more tomorrow if the problem's still around.

**Comment by Masuzu** [comment] 2017-12-21 09:32
Could it be this https://github.com/Masuzu/ZooeyBot/issues/447?

**Comment by Bone888** [comment] 2017-12-21 09:50
I'm also getting the same issue with 'Something went wrong trying to select a summon...' 

I tried the 'auto-popup' thing on viramate, but it didn't fix anything. It simply chooses the summon but doesn't endup pressing OK and just refreshes the page/chooses summon on loop.

**Comment by Masuzu** [comment] 2017-12-21 09:53
Ok I will look into it.

**Comment by SCHemerSheep** [comment] 2017-12-21 10:10
Zoeybot only can't lock on "OK" on Xeno Diablo EX. I tested Halo and the Light trial, both good.
![img_1116](https://user-images.githubusercontent.com/34738875/34251125-ded138fe-e5f3-11e7-82a7-b33fade3d394.PNG)

**Comment by Maestro93** [comment] 2017-12-21 14:18
Any updates on this issue?

**Comment by Masuzu** [comment] 2017-12-21 14:45
https://github.com/Masuzu/ZooeyBot/issues/447
I am afraid that you will need to wait at least 5 hours from now.

**Comment by jpgodkit** [comment] 2017-12-21 17:32
I am the same problem , I had re-install the chrome but this is happen again

**Comment by Masuzu** [comment] 2017-12-21 19:09
There is nothing you can do for now. Please just wait for the next release I am working on.

**Comment by Masuzu** [comment] 2017-12-21 21:58
Fixed in v2.4.3
https://poker-bot.azurewebsites.net/ZooeyBot/en/Home/PatchNotes#2-4-3

**Closed by Masuzu** 2017-12-21 21:58 UTC
Labels: bug, high priority
