### ISSUE TITLE
zooey bot stops while farming gw nm 90

### ISSUE THREAD

**Issue by location900** [Masuzu/ZooeyBot#572] opened 2018-02-15 03:19 UTC
I want zooey bot to use clarity herbs on party members charmed or strong armed. I use UseClarityHerbOnPartyMember(X) in my lua scripts but zooey bot stops after using the clarity herb and shows an error box as follow.  After i delete UseClarityHerbOnPartyMember(X), everything works well.
![2](https://user-images.githubusercontent.com/28516267/36239107-003af5e6-1242-11e8-971f-f8e2026004d3.png)

**Comment by Masuzu** [comment] 2018-02-15 21:28
I will look into it later during this GW.

**Comment by Ramkm77** [comment] 2018-02-16 19:47
Getting the same error . Hope can found a solution soon 😁. Thx

**Comment by Masuzu** [comment] 2018-02-16 23:40
Are you using Viramate or not?
I can't reproduce the issue (using Viramate).

**Comment by violafayde** [comment] 2018-02-17 04:34
same problem. I tried adding a wait before, and also tried after as follows:
if character_1:HasStatusEffect("1012_1") then
  UseClarityHerbOnPartyMember(1)
  Wait(4000)
end

if character_1:HasStatusEffect("1012_1") then
  Wait(4000)
  UseClarityHerbOnPartyMember(1)
end

the bot hung with the same error in both cases.

**Comment by kamohati** [comment] 2018-02-17 09:05
Hi, My zooey have same error, and I'm using viramate.
I tried adding delay, but zooey hung.

**Comment by Masuzu** [comment] 2018-02-17 12:08
Good news, I found out what the issue is. It only affects some raid battles. I will fix this.

**Comment by kamohati** [comment] 2018-02-17 12:10
Thanks:D

**Comment by Masuzu** [comment] 2018-02-17 12:34
This is now fixed in v2.9.3.

**Closed by Masuzu** 2018-02-17 12:34 UTC
Labels: bug
