### ISSUE TITLE
New type of anti-botting verification

### ISSUE THREAD

**Issue by zcdragon** [Masuzu/ZooeyBot#579] opened 2018-02-15 07:12 UTC

**Comment by ryokage** [comment] 2018-02-15 07:32
Yeah its new for sure it looks like this https://media.discordapp.net/attachments/170764997230723072/413591697981964299/Screenshot_20180215-140409.jpg?width=373&height=664

**Comment by ryokage** [comment] 2018-02-15 07:33
You have to click on it or it'll ban you or wont let you choose a different summon

**Comment by Masuzu** [comment] 2018-02-15 09:18
Hello,
Zooey Bot already supports this kind of anti bot detection:
Make sure to set the configuration parameter `MaxNumSummonSelectionFailuresBeforePlayingSoundNotification` to a value low enough (for instance 2 or 3).
After this amount of times failing to select a summon due to this popup, then the sound alarm will play until you stop it.

**Comment by Masuzu** [comment] 2018-02-15 09:20
https://github.com/Masuzu/ZooeyBot/issues/581

**Comment by Masuzu** [comment] 2018-02-15 09:21
For now, if you use Viramate, please make sure to disable the auto close popup feature.
![image](https://user-images.githubusercontent.com/5464705/36249100-ea5f6bd8-1239-11e8-9971-3ae0258558e4.png)

**Comment by calvinhyang** [comment] 2018-02-15 09:51
@Masuzu I'm not sure if that's a fix, because I have that setting on and wasn't alerted at all. 
The way this captcha works  is that it hides all summons except one per tab, so if the desired summon you want is missing, it will try to reroll for the summon in trial mode. The verify button doesn't exist in trial mode though and all the hidden summons reappear, and if the desired summon is found zoe will just start botting in trial mode. (This is what happened to me).

And I'm not sure because it isn't exactly possible to recreate, but if the desired summon is found in the one available summon, and you end up picking the summon instead of verifying with the captcha, that would be a huge red flag.

**Comment by Iysoni** [comment] 2018-02-15 09:55
Nooooooooo I just got banned till March 17th... Wasn't alerted at all :(
Best to hold off on botting for now until a solution is found.

**Comment by Alissa1122** [comment] 2018-02-15 09:56
Hi Masuzu,

Since this captcha doesn’t prevent you from selecting summon, if the remaining summon happens to be the preferred summon, I think Zooey will select it? If so it still trigger the anti-cheat flag I think, Cygame just set a trap for bots by not preventing bot from selecting summons, so they can tell who is human (select captcha button) and who is bot (select summon directly)

**Comment by Masuzu** [comment] 2018-02-15 10:10
@calvinhyang Oh, I get it. The issue is that the count for `MaxNumSummonSelectionFailuresBeforePlayingSoundNotification` is reset when Zooey rerolls the summons while it should not.

**Comment by Masuzu** [comment] 2018-02-15 10:11
@Alissa1122 The thing is that you can't select a summon if the popup appears, unless I missed something.

**Comment by straufe** [comment] 2018-02-15 10:11
oh my... i got baan from that T-T [https://prnt.sc/if0u8h](url)

**Comment by Alissa1122** [comment] 2018-02-15 10:20
@Masuzu Actually you "can" select the only remaining summon when the popup appears, and if bot keep ignoring the popup and select the remaining summon for many times (from twitter information, about 10~20 times), they will ban this account for 1 month (till Mar-17)

**Comment by calvinhyang** [comment] 2018-02-15 10:22
The captcha basically tries to trick bots into picking summons instead of the verify button. It's lucky that I accidently got stuck in trial mode.

**Comment by Masuzu** [comment] 2018-02-15 10:23
@Alissa1122 Thank you. This relates to the 3rd post of https://github.com/Masuzu/ZooeyBot/issues/577

_Posts may be deleted later on as this is sensitive info_

**Comment by Masuzu** [comment] 2018-02-15 10:42
A workaround will be released in 12h from now.
Forgive me if posts are deleted, all of them are very helpful but your safety goes first!

**Comment by zannettsama** [comment] 2018-02-15 17:39
thoughts on maybe having the bot be semi-manual? so zoey bot doesnt take over until in battle but navigating the menus and summons will be manually done

**Comment by Masuzu** [comment] 2018-02-15 18:43
@zannettsama I will consider it, but not right in the next release intended to fix the major issue first.

**Comment by Masuzu** [comment] 2018-02-15 21:27
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr"><a href="https://twitter.com/hashtag/ZooeyBot?src=hash&amp;ref_src=twsrc%5Etfw">#ZooeyBot</a> Now going back to grinding GW 😋<a href="https://t.co/fuq5ezPNKj">https://t.co/fuq5ezPNKj</a></p>&mdash; GBTools (@GBFPokerBot) <a href="https://twitter.com/GBFPokerBot/status/964249236794675200?ref_src=twsrc%5Etfw">February 15, 2018</a></blockquote>

**Closed by Masuzu** 2018-02-15 21:27 UTC
Labels: bug, high priority, informational
