### ISSUE TITLE
Event raid hosting with item requirements (GW nightmare modes and company)

### ISSUE THREAD

**Issue by greatmany** [Masuzu/ZooeyBot#86] opened 2017-05-31 16:50 UTC
when i set it to
`EventRaidUrl=http://game.granbluefantasy.jp/#quest/supporter/719091/1/0/10220`
for the current event the bot not run after initializing

only when i cut the url down to this shortened url the bot will run normally
`EventRaidUrl=http://game.granbluefantasy.jp/#quest/supporter/719091/1`
however the game will return an error after choosing summons so I need to use the longer URL

![screenshot 2017-06-01 00 49 27](https://cloud.githubusercontent.com/assets/28790334/26643545/449b226a-4664-11e7-98ee-ecd2b5771d0e.png)

**Comment by MonaSaySleep** [comment] 2017-06-01 01:54
I am getting the same issue. It will not work with http://game.granbluefantasy.jp/#quest/supporter/719091/1/0/10220

**Comment by kiunch** [comment] 2017-06-01 02:31
Same problem here, I guess we were all trying to do Prismaprawn event raid?

**Comment by MagCat** [comment] 2017-06-01 07:12
Shame that we are not gonna get this resolves before June 8 (possibly), since the author is having some issue until late June apparently. Anyways, here is my report.

At first my version 1.8.1 is stuck at the event home page. I notice you can't simply just paste url of the boss, since I tried to do it myself and the game can't even load the summon list. I had to refresh and rerun bots a few times until bot finally bypass the item requirement to get to summon list page. After that I got the (probably same) error after choosing a summon.

Error Code: B-001-98623
Network Error

After getting the error, bot chooses to click okay and goes back to summon list. This time instead of choosing the summon it just choose random Wind summon instead (Anat for example), then game just tells you another error again but this time bot doesn't even know how to go back.

**Comment by Masuzu** [comment] 2017-06-01 08:51
Hi,

The aforementioned issues are the same the ones encountered during the past GW when some people were trying to host nightmare raids, due to the game performing an additional "item check" beforehand.

A fix for this to farm the current event could be released before the end of the event.
As for the upcoming GW, I am not sure whether I will have the time to do it.

**Comment by kiunch** [comment] 2017-06-01 16:30
Thanks for the quick response! I want to add that the issue is not that "item event wouldn't work". It is a problem but both me and op had a different problem.

When the URL of the event raid is too long, the bot would just stop after "zooey bot initialized". After clearing network history, the mouse would stop moving (normally it would move to the address bar to paste the URL). It works completely fine when I used event raid with shorter URL.

**Comment by Masuzu** [comment] 2017-06-02 10:30
@kiunch Actually it is not an issue with the URL being too long but its format which is different from "regular" raid URLs.

**Comment by Masuzu** [comment] 2017-06-02 20:46
Experimental support for this feature was added in version 1.9.0:
 https://poker-bot.azurewebsites.net/ZooeyBot/en/Home/PatchNotes

**Comment by elp-l** [comment] 2017-06-02 23:18
New `[TreasureEventMode]` feature works to enter quest for both VH and EX, correctly selects support summon according to the `[Summons]` config parameters.

In combat the feature does not appear to use the assigned `[Combat]:LuaScript` nor the `[EventMode]:EventRaidScript`, instead attacking.  After attacking the page will reload if the `[Combat]:ReloadPageOnLastBattle` is set to true, or wait for the attack button to become active again if set to false.

Testing the same script using `[Debug]:TrialBattleMode` initiating combat mode in the VH event quest functions as expected with the lua being read and executed.

**Comment by Masuzu** [comment] 2017-06-03 12:20
Hi, this is fixed in v1.9.1 with the new parameter `TreasureEventModeScript`

**Closed by Masuzu** 2017-06-03 12:20 UTC
Labels: bug, enhancement
