### ISSUE TITLE
Unable to farm the new "Many Lives of Cats" EX raid

### ISSUE THREAD

**Issue by Anelfe** [Masuzu/ZooeyBot#1032] opened 2019-02-01 11:22 UTC
To give context to the issue in the title, since the EX raid has a "meat" equivalent of a requirement, I have used the *Treasured Event Mode* to try to farm this event, however it would get stuck at the summoning page and would need to navigate back to the event page url to continue, as seen here.
![screenshot_1038](https://user-images.githubusercontent.com/39061650/52119185-aa25e380-265b-11e9-9520-ee0ff63685a7.png)
![screenshot_1037](https://user-images.githubusercontent.com/39061650/52119187-aa25e380-265b-11e9-8795-771a439ec3bd.png)
The chunk of "New Page Loaded" from the Raid URL to My Page to Event URL is done by me while the bot is stuck.

So I have attempted to use the regular *Event Mode* to farm EX instead, it would work for around 5 raids then GBF would give an error and would inevitably redirect itself to the gacha page and be stuck there.
![screenshot_1040](https://user-images.githubusercontent.com/39061650/52119863-e65a4380-265d-11e9-98a5-d1511fe5df41.png)
![screenshot_1039](https://user-images.githubusercontent.com/39061650/52119873-ee19e800-265d-11e9-812e-64d8a68d2e67.png)

Oddly enough, if I do the normal way of initiating the EX raid (i.e Not touching the url, as inputting the raid url would continue giving the error) it would reset and allow the bot to continue as per usual before GBF gives the error around 5 raids in.
The raid URL I inputed for *Event Mode* is: http://game.granbluefantasy.jp/#quest/supporter/738301/1
The raid URL I inputed for *Treasured Event Mode* is: http://game.granbluefantasy.jp/#quest/supporter/738301/1/0/10304
As inputting the full url for *Event Mode* would cause to bot to get stuck after calibration.
Hopefully, I'm not missing a simple fix on my end, Thanks for reading.

**Comment by Masuzu** [comment] 2019-02-01 19:21
Hello,
I am planning to farm the EX mode this week-end and will therefore give it a second look0
In the meantime, this is what I use/
https://github.com/Masuzu/ZooeyBot/issues/1034

**Comment by Masuzu** [comment] 2019-02-01 21:40
Confirmed to be working as intended, therefore closing.

**Closed by Masuzu** 2019-02-01 21:40 UTC
Labels: question
