### ISSUE TITLE
Angel Halo NM transform detection issue

### ISSUE THREAD

**Issue by crazeefella** [Masuzu/ZooeyBot#169] opened 2017-07-25 01:42 UTC
Hi,

I have been using the event section of the script to perform Angel Halo NM farming. Everything works fine except for the detection RetreatWhenNoDimensionalHaloTransformation=true

This field does not seem to work and it does not detect when the Angel Halo NM will transform. Are there any other additional configurations I need to perform?

**Comment by Masuzu** [comment] 2017-07-25 11:12
It could be that the ID of the Dimensional Halo boss was changed.
As it is hard to test, I probably will add an option to retreat if the given enemy ID is present in the raid.

**Comment by crazeefella** [comment] 2017-07-26 14:21
I think the ID did not change, I have a bookmarklet created to run it and check for me. It has been accurate when I run that bookmarklet which is based on the ID 6005070 to test if it transformed.

Only when I run the bot that flag does not seem to take effect.

**Comment by Masuzu** [comment] 2017-08-06 12:15
I can confirm the issue but not the cause. I will see what I can do.

**Comment by Masuzu** [comment] 2017-08-07 22:39
Good news, I found out what the issue was. I will release a patch for this within 48 hours.

**Comment by Masuzu** [comment] 2017-08-07 23:58
It seems that the enemy ID of the Angel halo when it does not transform is now 8300063.

**Comment by IZEROII** [comment] 2017-08-08 03:13
thank you for getting back to us on this issue and providing support

**Comment by Masuzu** [comment] 2017-08-08 17:58
This should be addressed in version 1.14.2
https://poker-bot.azurewebsites.net/ZooeyBot/en/Home/PatchNotes#1-14-2
I could test it first-hand on my side :)

**Closed by Masuzu** 2017-08-08 17:58 UTC
Labels: bug
