### ISSUE TITLE
Rerolling for summons only goes to trial battle on first reroll attempt

### ISSUE THREAD

**Issue by ycalvin** [Masuzu/ZooeyBot#54] opened 2017-05-18 07:27 UTC
Been using Zooey to farm EX+ for Guild Wars. When a preferred summon is not found, it will go to trial battle and retreat normally. On the second and on reroll attempt, it will instead start rerolling on the quest specified in "EventRaidUrl" under "[EventMode]" so it's rerolling on EX+ dog instead of trial battles.

**Comment by Masuzu** [comment] 2017-05-18 07:40
Again, that's troublesome indeed.
I will check this bug later.

**Comment by ycalvin** [comment] 2017-05-18 07:46
[ZooeyBot.txt](https://github.com/Masuzu/ZooeyBot/files/1010109/ZooeyBot.txt)

Here are my configuration settings in .txt format in case it is a problem that I caused by overlooking something.

**Comment by Masuzu** [comment] 2017-05-18 18:49
I identified the cause of the bug causing the issue you mentioned.
It will be fixed in the version 1.5.3.

**Comment by Masuzu** [comment] 2017-05-18 18:59
Fixed in version 1.5.3: https://poker-bot.azurewebsites.net/ZooeyBot/en/Home/PatchNotes

**Closed by Masuzu** 2017-05-18 18:59 UTC
Labels: bug
