### ISSUE TITLE
Refreshing bug in coop mode (critical)

### ISSUE THREAD

**Issue by Dreamfinal** [Masuzu/ZooeyBot#147] opened 2017-07-04 03:26 UTC
Hello
I want to report to you.

**Refreshing bug in coop mode**

In normal state, after entering the lobby, the bot will automatically select the 'ready start' button. But  sometimes the bot doesn't work normally. It chooses URL and keeps refresh both IDs continuously until time's up.
The problem is if I start the program for 10 minutes and left the keyboard to do something else (like working or sleeping) and the bot occurs, I will lose the buff item and 50 minutes of time for nothing.

I want you to fix this bug as soon as possible. The damage is double when combined with the random ID detection bug (the previous issue that I sent you).

-For your information, the random ID detection bug occurs everytime. 
-Refreshing bug has approximate 33% chances to occur (every 3 hours for one encounter). It isn't frequent as the above bug.

**Comment by Masuzu** [comment] 2017-07-04 23:34
About the wrong player ID being detected, you should wait keep your browser window active as long as the console does not display the correct player ID, and make sure not to have several Chrome Devtools window opened at the same time.

If the ready start button is already selected at the start, the bot will keep refreshing both window indefinitely.

**Comment by Dreamfinal** [comment] 2017-07-05 07:15
Here's the thing. This is definitely bug not user error. The first bug, the random one, no matter how you open the chrome newly or leave it like that, the bug still goes on. I temporarily solved this by repeat closing and opening chrome until the bug is gone by itself.

But the other one is an issue I can't handle with. It is a very critical one. There is where the bot stays still at ready start interface, keep refreshing the url continuously. It remains like this for a long time. It's not the same case in which you've replied me. I didn't do anything to it. But I guess, there are chance that the speed of the internet had dropped and this might cause the bug to occur.
So I would like to make a request. Could you make the bot pushs 'start' straightforward without refreshing itself when the 'start' button's condition  is blue? This would help us a lot. Thanks for the reply and I look forward to hearing from you.

**Comment by Masuzu** [comment] 2017-07-06 20:51
Hi,

Thank you for the details. I will look into it this week end.
The bot tries to check whether the ready button is blue. If it is not after X amount of time, the bot will refresh the page and check again. If the webpage did not load before X seconds, then the bot will refresh the page again.
I can add increasing delays but will look into this again. Usually I have a very stable internet connection so I never faced this issue, but as I said I will take a closer look this week-end.

**Comment by Masuzu** [comment] 2017-07-06 21:28
Actually I am not sure of how on earth you run into this issue.
There is already an increasing delay between each refresh so the start and ready button are both fully loaded.
Is the ready button pressed?
The configuration parameter `MinWaitTimeInMsAfterRefresh` configures the initial waiting time after a page refresh.

**Comment by Dreamfinal** [comment] 2017-07-07 19:31
Hi,
Today I have two topics I want to discuss with you. 
The first one is random ID bug that no matter what action were taken, the bug still exists. 
The second topic is the refreshing bug, I understand what you've discussed in the previous reply, but I don't remember what the parameter said.

For the first topic, I've tried your guidance in the link https://github.com/Masuzu/ZooeyBot/wiki/Slave-mode-(slime-basting) and in the youtube https://www.youtube.com/watch?v=9EIDg5WM1VU . 
I've followed every steps that you have shown in these sources. 
Oh and don't worry! I'm also a programmer, I'm certain that it is not a user's mistake.
However, after I tried everything you have shown, the bug is still at large. 
It's never gone and significantly appear almost every times when I run the bot. 
There's only a rare chance that it will work properly in one go.
 After I've tried these and they didn't work for me, I try out other ways to find the source of the problem, what I did are;
- I opened one Chromedev at a time,
- I opened the main ID before the slave,
- I opened the slave ID before the main,
- I refreshed ID (F5) and clear Chromedev just one window,
- I refreshed ID (F5) and clear Chromedev two windows,
- I clicked the button 'Home' and went to the 'Co-op',
- I closed the entire windows (not the tab).  

All I did couldn't change the situation. The bug is still there and remains the same occurrence. 
Even fast clicking and slow clicking didn't work as well.
I really have no idea how to deal with this or even know the source of problem. 
The bug is pretty serious and take quite a lot of time to get it work normally.

The second topic is the refreshing bug that we've been talking about the relevant to internet connection.
The part you asked for what my console was texting, I forgot what it said at the moment the bug was occurring. So if it happens again, I'll make sure to record you the video and get most of the information to help update for you.

   Thank you for your help and kind support. You've been working really hard and I'm really appreciate your dedication to end these problems. I look forward to hearing from you again.

**Comment by Masuzu** [comment] 2017-07-08 11:28
Hi,

I have good news! I could reproduce the player ID bug too, by having both extensions enabled in incognito mode. It looks like allowing only the slave extension in incognito mode solved the problem for me: https://github.com/Masuzu/ZooeyBot/wiki/Slave-mode-(slime-basting)#other-important-remarks

**Comment by Dreamfinal** [comment] 2017-07-08 18:12
I've tried your incognito mode suggestion, it works! Thank you very much!

For the refresh bug, I'm not sure if the code is the same as your reference. So I'll capture the screen when it appears again.

Unfortunately, I found another issue related to the refresh bug. The current 'refresh bug' is probably caused by the delay of the internet connection. However if the network error happens (see the attached picture), the bot will stop working until I manually click 'ok'. 
For your information, I set my main ID to attack first. So when network error occurs, the main doesn't load and the slave waits for the queue and nothing moves on. The bot sits still until I click 'ok' and it works normally again. 
This is not a serious one. Pretty much a very rare case. I've been using the bot for a long time and this is the first time it happens to me. So don't worry! You can   work on priority tasks before looking into this new issue. 
Thank you for your effort. I'm very pleased with the results.

http://i3.photobucket.com/albums/y86/dreamfinal/PhotoGrid_1499534071009_zpsmgytsps3.jpg

**Comment by Masuzu** [comment] 2017-07-09 22:11
Ah, thank you for the report of the "Network Error" popup window. I will see if I can make some changes the upcoming week to automatically dismiss this error popup should it appear,
Setting Internet connection issues aside, if you have ongoing raid battles which just ended or performed another action on your account (for instance, a party member change or changing your grid or upgrading weapons) at the same time as the page was reloaded, you are more likely to run into this kind or error, from personal experience.

**Comment by Shamool** [comment] 2017-07-16 14:14
Not sure if I should post this here because it has to do with refresh as well, but recently while sliming, I've noticed that the bot refreshes the room once before it continues on. It only does it even when the button is there and ready to be pressed. Though after it refreshes once it continues on.

![slime error](https://user-images.githubusercontent.com/30111700/28248241-ef46586e-6a73-11e7-9605-4e5773111cf1.PNG)

**Comment by Shamool** [comment] 2017-07-19 02:53
![slime error](https://user-images.githubusercontent.com/30111700/28348563-4a4a3fd4-6c70-11e7-92b0-9cc1226e813a.PNG)
Posted this on this thread before taking it down to try some stuff. Didn't work, so I'm reposting it. Not sure if it is my network, but while sliming, the bot always seems to refresh the room once before going on, despite the buttons there.

**Comment by Masuzu** [comment] 2017-07-20 20:08
It can happen, sometimes. I won't fix this as it is not a regular occurrence and does not block the bot from going on.

**Closed** 2017-07-25 11:14 UTC
Labels: bug
