### ISSUE TITLE
Possible incorrect charge bead count

### ISSUE THREAD

**Issue by salvanost** [Masuzu/ZooeyBot#400] opened 2017-11-15 07:38 UTC
please help me...

i got some problem with the lua script
using charlotta as character_3
i want to 50% damage cut shield before the boss charge attack
the script only works for under 50% hp(the diamond charge is 2)
it's not working for earlier battle with hp >= 51 (the charge diamond is 3)

> 
> if enemy_1.hp_percentage >= 51 and enemy_1.charge_diamonds == 4 then
>     character_3:UseSkill(2)
> end  
> 
> if enemy_1.hp_percentage <= 50 and enemy_1.charge_diamonds == 3 then
>     character_3:UseSkill(2)
> end  
> 

i also using sage to heal my party
using Mazusu nm95 script

> --[[Helper functions]]
> function NumCharactersBelowHPPercentage(percentage)
>   local sum = 0
>   for name,character in pairs(characters) do
>     if character.hp_percentage <= percentage then
>       sum = sum + 1
>     end
>   end
>   return sum
> end
> 
> if NumCharactersBelowHPPercentage(70) >= 2 then
>   character_1:UseSkill(1)
> end
> 
> if NumCharactersBelowHPPercentage(45) >= 2 then
>   UseSupportPotion()
> end

works fine for sage panacea skill 1
but dunno why the support potion not working,
got error pop up runtime error while trying to use support potion

**Comment by Masuzu** [comment] 2017-11-16 13:13
Hi,
Support potions work fine on my side.
As for the charge diamond count which seems not to be working as intended, I'm afraid I won't have the time to debug this issue before the end of the GW, sadly.

**Comment by salvanost** [comment] 2017-11-16 15:08
Don’t worry Mazusu
No UnF at Desember

**Comment by Masuzu** [comment] 2018-09-23 10:33
Addressed in previous versions

**Closed** 2018-09-23 10:33 UTC
Labels: low priority
