### ISSUE TITLE
Bot stop doing NM after a while.

### ISSUE THREAD

**Issue by zappky** [Masuzu/ZooeyBot#983] opened 2018-12-05 14:18 UTC
I have recently noticed that in the latest version, the bot just stop doing NM after running for sometimes.

This consistently happen after around 30mins of botting. 
I keep noticing my NM having timer like 45mins,35 mins,etc when i come back to check on the game.

This keep happening and just to double check if it is because i put the url for nm wrongly ,i waited and checked if the bot is able to start NM and able to clear the quest. Well, it can successfully detect and clear it. 
However, after some time, the problem just come back again. 

Wondering if anyone else is experiencing the same thing.

I am using the latest version 3.3.1 and using Viramate as well.

Thank you.

**Comment by Masuzu** [comment] 2018-12-09 11:40
Hello,
I just can't seem to reproduce the same situation after more than one hour with the current event.
Screenshots of the console messages when it happens would help probably, thank you.

**Comment by moourns** [comment] 2018-12-09 18:56
I've had the same issue come up for the past 4 versions but always towards the end of the hour since I don't let Zooey for more than an hour. I'll keep an eye on the console next time it happens but is there a way to pause Zooey to look the console without closing it completely?

**Comment by Masuzu** [comment] 2018-12-10 18:17
Ah I see, another possibility for you to access log messages is to run ZooeyBot.exe from a console command line input. This way, when you stop it, you will still have those log messages available in the console even though the program exited.

**Comment by zappky** [comment] 2018-12-15 04:47
This issue is back again.  I just stop the bot just to check on NM. 
I saw the NM Halo is on 9 Mins left. I remember seeing it triggering and clearing NM halo on the first hour. This seems to be a tricky bug to catch because i wont know when it will happen and i wont be keeping an eye on the bot all the time too.

Is it possible to have debug log in txt file just logging all those error messages?

**Closed** 2019-06-01 10:01 UTC
