### ISSUE TITLE
crash after using summon

### ISSUE THREAD

**Issue by reinharto** [Masuzu/ZooeyBot#280] opened 2017-09-15 16:47 UTC
[ZooeyBot.zip](https://github.com/Masuzu/ZooeyBot/files/1307038/ZooeyBot.zip)

Regardless of my script, the bot crash after using summon. After it crash, I can't reopen zooeybot.exe. It automatically close after closing the pop up for the time remaining on the account. This happen to all of my script. I also atttach my ini. Edit: did some testing, only occur after summon, regardless of script. If I remove summon, no crash.

Ex:
if turn > 0 then
  Summon(6)
  character_2:UseSkill(2)
  character_1:UseSkill(4)
  character_1:UseSkill(1)
end

**Comment by Masuzu** [comment] 2017-09-16 14:03
Hi,
Could you please post a screenshot of the messages in the console when it crashes?

For like 99% of the users summons are working fine so it is a bit hard to see what the problem is.

**Comment by Masuzu** [comment] 2017-09-16 14:04
`It automatically close after closing the pop up for the time remaining on the account` It looks like an antivirus related issue/desperate corner case which would happen in a minority of the cases...

**Comment by reinharto** [comment] 2017-09-16 15:43
Here is the screenshot. https://i.imgur.com/VrFZyPv.jpg
Here a gif of what happen when I run it with summon. No crash or anything without summon

**Comment by Masuzu** [comment] 2017-09-18 10:11
Ah, I got it now.
Please make sure not to set for the parameter `ExitKeyCode` the code of the escape or space key, or any of the keyboard shortcuts used by Viramate. Otherwise you will run into this exact situation. By default the value 112 is set, which means that whenver you press the F1 key, the bot will close.

**Closed by Masuzu** 2017-09-18 10:11 UTC
Labels: help wanted, invalid
