### ISSUE TITLE
Treasure Event Mode ExMode Not Working

### ISSUE THREAD

**Issue by Zuser120000000** [Masuzu/ZooeyBot#470] opened 2018-01-03 08:29 UTC
In the event currently being done, since HighLevel has appeared, ExMode can not be used.

**Comment by Mitsukai** [comment] 2018-01-03 09:31
Just confirming; it hangs after opening the menu where you select Extreme or Impossible/HL.

**Comment by violafayde** [comment] 2018-01-03 16:07
I can confirm this is happening. Unable to farm extreme right now.

**Comment by violafayde** [comment] 2018-01-04 09:30
has anyone found a workaround for this yet?

**Comment by Inroi** [comment] 2018-01-04 11:37
Same issue here.

Think might be the problem of the new HL

**Comment by Masuzu** [comment] 2018-01-04 19:20
Hello,

I am aware of this issue and took note of it.

**Comment by violafayde** [comment] 2018-01-04 20:38
thanks, hopefully we can get a fix soon, i have 700 mats waiting to be hosted :3

**Comment by filipi159951** [comment] 2018-01-05 00:59
i can't farm the Very Hard level, event mode comes to Mypage, and Treasure event mode stops on summon page.
What should i do?

**Comment by fourteeth** [comment] 2018-01-05 02:35
@filipi159951 

You must paste the event main page on it.

For example，EventPageUrl=http://game.granbluefantasy.jp/#event/treasureraid063

**Comment by filipi159951** [comment] 2018-01-05 02:48
@fourteeth i did it, but zooey don't go to the event page, it try to put the raid code, and it goes to My page...

[EventMode]
 Set this parameter to true to use the event mode. Zooey will enter autopilot mode when you navigate to the quest menu.
Enabled=true
 Url of the summon selection page for the Xeno Diablo Extreme mode
EventRaidUrl=http://game.granbluefantasy.jp/#quest/supporter/724591/1
EventRaidScript=Scripts/Right Behind You.lua
 Url of the summon selection page for the Xeno NM 70 mode
NightmareModeUrl=
NightmareModeScript=Scripts/Right Behind You_nm.lua
 Some events such as Rise of the Beasts require to navigate to the home page of the event before navigating to the event raid url defined above. If EventPageUrl is provided, Zooey will first navigate to this url before hosting the raid. Leave EventPageUrl blank for events which do not require you to do so.
EventPageUrl=http://game.granbluefantasy.jp/#event/treasureraid063
 Comma-delimited list of summons which will be selected in priority if they are available for the nightmare mode.
 In case none of the preferred summons was found, select a random summon in the summon attribute tab defined by the parameter DefaultSummonAttributeTab, unless the parameter RerollSummonWhenNoPreferredSummonWasFoundForNightmareMode is set to true.
NightmareModePreferredSummons=Bahamut
Zooey will reroll summons until one of the preferred summons for the nightmare mode is available, using trial battles to refresh the summon list.
RerollSummonWhenNoPreferredSummonWasFoundForNightmareMode=true
Set this parameter to true if the nightmare mode is available when you start Zooey so she can proceed to the nightmare stage right ahead.
NightmareModeAvailableAtStart=false
Wait time in milliseconds after Zooey finishes loading the EventPageUrl
WaitTimeInMsAfterEventPageIsLoaded=0

that's my code

**Comment by Lurline** [comment] 2018-01-05 03:17
@filipi159951

I was having the same issue. What I did to fix it was change `WaitTimeInMsAfterEventPageIsLoaded=0` to `WaitTimeInMsAfterEventPageIsLoaded=1000`. It fixed it for me now, so maybe try that or if that doesn't work maybe set an even higher wait time. Hope it helps you. :)

**Comment by filipi159951** [comment] 2018-01-05 03:40
worked @Lurline Thanks

**Comment by violafayde** [comment] 2018-01-07 06:00
is the update coming soon? just wanna know because the event is ending soon :(

**Comment by meteoshower** [comment] 2018-01-07 07:15
yeah i need to know too so i stack old rune cube about 2800  for extreme  bot  );

**Comment by Masuzu** [comment] 2018-01-07 23:20
This is now fixed with v2.4.5:
https://poker-bot.azurewebsites.net/ZooeyBot/en/Home/PatchNotes#2-4-5

**Closed by Masuzu** 2018-01-07 23:20 UTC
Labels: bug

**Comment by meteoshower** [comment] 2018-01-07 23:50
Wow that's great 2.4.5 Work fine thanks Misuzu
