### ISSUE TITLE
Cygames making counter measures against ZooeyBot?

### ISSUE THREAD

**Issue by iDorkyKenny** [Masuzu/ZooeyBot#165] opened 2017-07-16 20:08 UTC
http://game.granbluefantasy.jp/#news/detail/1473/2/1/1

**Comment by Masuzu** [comment] 2017-07-17 07:54
Duplicate of https://github.com/Masuzu/ZooeyBot/issues/164

**Closed by Masuzu** 2017-07-17 07:54 UTC
Labels: duplicate
