### ISSUE TITLE
Crashes in 2.0.0 - failed to parse Ability result

### ISSUE THREAD

**Issue by Shamool** [Masuzu/ZooeyBot#335] opened 2017-09-30 12:48 UTC
After updating to Vers 2.0.0, I seem to be unable to use Andriia's third skill. 

if turn==1 then
 DisableChargeAttack()
 character_1:UseSkill(2)
 character_1:UseSkill(3)
 character_1:UseSkill(4)
 character_2:UseSkill(3):WithWaitTime(3000)
 character_3:UseSkill(2)
 character_3:UseSkill(3)
 end

if turn==2 then
 character_1:UseSkill(1)
 end

if turn==4 then
 Summon(6)
 EnableChargeAttack()
 character_4:UseSkill(2):WithWaitTime(4100)
 end

This is the lua script I use for the current even VH, 2.0.0 will crash when Andriia uses skill(3). This script works fine with Vers 1.22.0.

**Comment by GumiFlatline** [comment] 2017-09-30 12:56
Same problem here, with almost the same script. Zoibot runs the first 5 lines normally, but it crashes in the 6th line, when it supposed to use Orchid's 3rd skill.

**Comment by Shamool** [comment] 2017-09-30 13:11
From what I see, I think it centers around some characters skills? I changed party order, moved the skill order up and down; the crash only happens when Andriia's Skill 3 comes out.

**Comment by GumiFlatline** [comment] 2017-09-30 13:18
Yeah, same here. It only crashes when using Orchid's 3rd skill, but not when using MC and Seox respective 3rd skills.

I didn't test it without using Viramate keybind function though. Are you using Zoibot with Viramate?

**Comment by Shamool** [comment] 2017-09-30 14:07
Yes, I use the bot with Viramate's keybind function.

**Comment by vyrnstrument** [comment] 2017-09-30 15:19
Does 2.0 crash for anyone else in coop slave mode? I have my main account attack first, followed by slave account, but Zooey always crashes after the slave presses "attack". Both use Viramate and have keyboard shortcuts enabled. No issues with previous versions of Zooey.

**Comment by GumiFlatline** [comment] 2017-09-30 15:53
Maybe it's a problem with Viramate's keybind function. I'm running Zoibot (Treasure Mode) without issues after disabling Viramate, with the same party and script as before.

**Comment by ryokage** [comment] 2017-10-01 22:34
I'm having the same problem. Its definitely a bug with 2.0 with viramate. I was running into a bunch of crashes until I disabled viramate @Masuzu

**Comment by fumika779** [comment] 2017-10-02 02:56
@Shamool  

character_2:UseSkill(3):WithWaitTime(3000)

it crashes in this line because  Manazu change   <WithWaitTime> 's syntax

You can also customize the waiting time after using an ability with the following syntax: characters["Orchid"]:WithWaitTime(<wait_time_in_milliseconds>):UseSkill(<skill_index>) Otherwise, Zooey will wait by default for MinWaitTimeInMsAfterAbility after using any ability.
>>https://github.com/Masuzu/ZooeyBot/wiki/Lua-scripts

however I crashes in another line. 
(when Jeanne<dark> use skill 2) 
bot is stopping

**Comment by fumika779** [comment] 2017-10-02 03:00
@Shamool

character_2:UseSkill(3):WithWaitTime(3000)

it crashes in this line because Masuzu change  WithWaitTime 's syntax.

You can also customize the waiting time after using an ability with the following syntax: characters["Orchid"]:WithWaitTime(<wait_time_in_milliseconds>):UseSkill(<skill_index>) Otherwise, Zooey will wait by default for MinWaitTimeInMsAfterAbility after using any ability.
>> https://github.com/Masuzu/ZooeyBot/wiki/Lua-scripts

but I crashes in another line.
(after Janne<dark> use skill 2)
and I don't use viramate

**Comment by readmynameplease** [comment] 2017-10-02 10:49
I'm using this script : after beatrix cast the 2nd skill for overdrive enemy it just crashed anyone can help me out?

if character_1.charge_gauge >= 100 then
  EnableChargeAttack()
else
  DisableChargeAttack()
end
if character_1.hp_percentage <=20 then
UseGreenPotionOnPartyMember(1)
end
if character_2.hp_percentage <=20 then
UseGreenPotionOnPartyMember(2)
end
if character_3.hp_percentage <=20 then
UseGreenPotionOnPartyMember(3)
end
if character_4.hp_percentage <=20 then
UseGreenPotionOnPartyMember(4)
end

-- # main character
character_1:UseSkill(2)
character_1:UseSkill(3)
character_1:UseSkill(4)

-- # Beatrix
if turn == 1 then
character_2:UseSkill(1)
character_2:UseSkill(1)
character_2:UseSkill(3)
end 

if enemy_1.overdrive_state then
  character_2:UseSkill(2)
  end

-- # Clarisse
character_4:UseSkill(1)
character_4:UseSkill(3)
-- # Grea
character_3:UseSkill(1)
if turn == 1 then
Summon (6)
end

**Comment by Masuzu** [comment] 2017-10-02 11:22
Hi,

@Shamool The script syntax changed as mentioned in the patch notes, and was updated in the Lua script wiki page...

It is not `character_2:UseSkill(3):WithWaitTime(3000)` anymore but `character_2:WithWaitTime(3000):UseSkill(3)`

**Comment by Masuzu** [comment] 2017-10-02 11:23
@vyrnstrument I will check it later.

**Comment by Masuzu** [comment] 2017-10-02 11:26
@readmynameplease I don't see anything wrong with the script syntax. Could you please post a screenshot of the console messages when it "crashes", or else nobody will be able to help I'm afraid.

**Comment by readmynameplease** [comment] 2017-10-02 11:35
@Masuzu here is a image [http://prntscr.com/gs9g3v](url)

**Comment by Masuzu** [comment] 2017-10-02 11:43
Are you using the same script that you posted a few lines above?
Just asking as the skills 1, 1 and 3 should have been used on the 1st turn.
Thanksfully I also happen to have SS Beatrix so I can see if it is a character related issue.

**Comment by readmynameplease** [comment] 2017-10-02 11:49
![222](https://user-images.githubusercontent.com/32391012/31075971-cf0bfc88-a7c3-11e7-9b13-09ae393c84f2.jpg)
![333](https://user-images.githubusercontent.com/32391012/31075974-d35d161e-a7c3-11e7-909c-6f6a69c18448.jpg)
here are the screenshots

**Comment by fumika779** [comment] 2017-10-02 12:35
![2017-10-02_091358](https://user-images.githubusercontent.com/31799116/31077441-b774be2c-a7a8-11e7-8540-f5d9113f003d.jpg)
![2017-10-02_193408](https://user-images.githubusercontent.com/31799116/31077442-b77806cc-a7a8-11e7-8a9e-686762bcc7fa.jpg)

**Comment by Masuzu** [comment] 2017-10-02 12:58
Ok, thank you, I see. It must be an issue with the result of the ability use.

**Comment by Masuzu** [comment] 2017-10-02 18:11
Good news, the cause of the crash was found and a fix will be released within the next 24 hours.

**Comment by Masuzu** [comment] 2017-10-02 19:17
Fixed in v2.0.1
https://poker-bot.azurewebsites.net/ZooeyBot/en/Home/PatchNotes#2-0-1

**Closed by Masuzu** 2017-10-02 19:17 UTC
Labels: bug, high priority
