### ISSUE TITLE
New anti-bot feature implemented?

### ISSUE THREAD

**Issue by kujaras** [Masuzu/ZooeyBot#577] opened 2018-02-15 07:11 UTC

**Comment by calvinhyang** [comment] 2018-02-15 07:13
Just encountered this too. 

It hides the summons, and zooey bot recognizes that the desired summon isn't available. 

The summons don't get hidden when you try to reroll in trial mode though, and zooey then enters trial mode with the desired summon and ends up just bashing on the trial monster forever. (This would also be a huge red flag for bot detection)

**Comment by Masuzu** [comment] 2018-02-15 10:17
@calvinhyang Thank you for the additional information.

**Comment by calvinhyang** [comment] 2018-02-15 10:30
It didn't try retreating from trial mode for me. Basically desired summon was hidden until it went to start a trial mode. When it recognized that desired summon was available(without even entering trial mode yet), it treated the trial mode boss as GW EX+ battle and just started running my EX+ script on the trial battle instead. 
I'd imagine this is caused by Zoe first checking for desired summon and if desired summon is found, it just assumes it's running as normal.

**Comment by Masuzu** [comment] 2018-02-15 10:33
I see. I managed to get a screenshot of the exact issue thanks to @Sundaerae
A workaround will be released in 12h from now.

**Closed** 2018-02-15 10:39 UTC
