### ISSUE TITLE
Slave Mode network errors

### ISSUE THREAD

**Issue by moonlee7777** [Masuzu/ZooeyBot#786] opened 2018-05-06 17:51 UTC
Slave mode picks up slave network signals and normal network signals from just the main client, and nothing from the slave client. So when I refresh the main client, it says both new signal found and new slave signal found. I tried this through ~30 trials, and everything came to the same result. I checked that I was clicking the right extensions, and double checked my settings. What's wrong?

**Comment by Masuzu** [comment] 2018-05-09 13:46
Hello,
This is always due to not following exactly the instructions detailed on:
https://github.com/Masuzu/ZooeyBot/wiki/Slave-mode-(slime-basting)#getting-down-to-business
Especially the parts mentioning closing the other devtools windows and https://github.com/Masuzu/ZooeyBot/wiki/Slave-mode-(slime-basting)#other-remarks as well.
I tested it again on the current Chrome official build (Version 66.0.3359.139 ) and it works as intended.

**Closed by Masuzu** 2018-05-09 13:46 UTC
