### ISSUE TITLE
Calling for backup

### ISSUE THREAD

**Issue by Michael12jan** [Masuzu/ZooeyBot#730] opened 2018-04-04 15:23 UTC
Hi,

Is it possible to call for backup on treasure event mode?

Thank.

**Comment by Masuzu** [comment] 2018-04-05 18:48
Hello,
I have no plan to do that for now as it leads the way to a whole lot of other different issues with Lua scripts not doing what you expect them to do anymore, due to the actions of the other players.

**Comment by zooeyjapan** [comment] 2018-04-30 14:46
Maybe an alternative would be, that cfb can only be called in the lua, and when it does, it stops any further actions (barring maybe auto attack) until the result screen appears?

But maybe not worth the time to implement the conditionals.

**Comment by breinjhel** [comment] 2018-09-20 08:14
Hi @Masuzu ,

Just having a lua function that does the call for backup is enough for most of us. usually just do few turns then call for backup then keep on auto attacking

**Comment by breinjhel** [comment] 2018-09-20 08:15
I really need this feature to make our life easier instead of focusing to the game 24/7 just to host M2 raids and whatnot we can just schedule raid do few turns and call for backup on all host raids

**Comment by Masuzu** [comment] 2018-09-21 09:16
Hello,
I will close this as it is a duplicate of https://github.com/Masuzu/ZooeyBot/issues/777

**Closed by Masuzu** 2018-09-21 09:16 UTC
