### ISSUE TITLE
Need help regarding Slime Slave

### ISSUE THREAD

**Issue by spongebear** [Masuzu/ZooeyBot#94] opened 2017-06-09 20:31 UTC
Alright so i bought the license and the angel halo farming works. However i'm increasingly frustrated trying to get the slimebot to work. 

I'm never ever able to get the 'new network requests' to appear. anyone got any idea what might went wrong?

**Comment by MagCat** [comment] 2017-06-10 02:13
Try to enable slave extension before master's extension. Even then, you might still get stuck at the beginning of battle where bot does nothing but copy-paste url. You will have to try to mess with the config more. The slime bot really rarely works for me.

**Comment by Masuzu** [comment] 2017-06-10 10:12
The issue with the bot reloading the page at the start of the battle is caused by bad ping (Aussie players or terrible ISP) and I can't do anything about this apart from making the delay before refreshing the page configurable, which was already done. There is another bug though which is that the slave ignores the script commands. I won't fix it before the end of the month unfortunately as I have no computer. With a stable ping of 17x ms I have no issues.
A workaround is just to use dark Jeanne sword or Sarasa on your main account. Tested a few minutes ago.

**Comment by MagCat** [comment] 2017-06-10 15:27
@Masuzu: that's really weird because I'm in US and I have a pretty decent internet speed. My laptop is pretty beefy (970m) so I know it shouldn't even be a problem from hardware either. I also made sure the laptop is connected to router with ethernet cable. About the bot ignoring script commands, that also happens with other modes currently. Though I'd prioritize fixing slime bot since it's more common to use for.

**Comment by okamijackie** [comment] 2017-06-11 06:03
does any one know how to make a script to use skills for fights i am not sure how to do that

**Comment by Masuzu** [comment] 2017-06-11 13:36
I will provide a fix for the slave mode script commands being ignored as I am using the slime blasting a lot at the moment and encountered some issues too with it.

**Comment by Masuzu** [comment] 2017-06-11 14:33
Lots of bugfixes:
https://github.com/Masuzu/ZooeyBot/issues/98

**Comment by i-Grey** [comment] 2017-06-11 17:25
Thank you for updating although you are super busy.

After I update to 1.9.5 and 1.9.6.
At least, slave account is already press skill but it's still stuck on the main account.

When the attack of the slave account is done and switching to main account attacking, the text "Waiting for Attack button to be active" appear and it's do nothing except keep refresh endlessly.

I would like to use Viramate too but you mention that the Viramate isn't safe doesn't it?
If it's completely safe I will try again and update the testing result.

**Comment by MagCat** [comment] 2017-06-11 19:22
@Masuzu unfortunately I still got the same exact problem just like all other versions. If it's any help, I make my main account attack first by setting the parameter to true. Bot still refreshes both account without doing anything.

**Comment by MagCat** [comment] 2017-06-12 03:19
Okay, I just tried to make slave account attack first, and one thing I found really interesting is like @i-Grey mentioned, the main account will be always stuck and get refreshed indefinitely..

Basically, something wrong going on across all versions from 1.3.2, 1.4.1, 1.6.3, 1.8.1, 1.9.0-7 that is very consistent right now that breaks slimebotting. 

If slave account attacks first, it works, but main account does nothing but refreshing indefinitely.

If main account attacks first, no skills gets executed but bot keeps refreshing indefinitely.

**Comment by i-Grey** [comment] 2017-06-12 10:25
I've already tried to use Viramate thought and it's still have the same problem.
It seems that I and MagCat meet the same problem.

FYI: I'm at Singapore and I think my connection has stable ping enough.

**Comment by Masuzu** [comment] 2017-06-13 03:22
I just can't reproduce any of the issues mentioned above with the version 1.9.7 with 2 sword masters, both using their first skill on my side. :thinking: 
I've been slime blasting just fine for several hours now with the version 1.9.7

**Comment by Masuzu** [comment] 2017-06-13 03:25
If both pages keep refreshing it means that the attack button on the slave window can't be detected, which should not happen normally as the delay between each refresh increased with each failure to detect the attack button unless I'm mistaken. Very weird.

**Comment by MagCat** [comment] 2017-06-13 04:17
I found a few interesting things to fix this issue on MY end. This is laptop only because I just found out this trick past few days ago trying to farm idolmaster event. The trick was simple, closing my laptop's lid, log-in account on Win10 again WHILE leave DevTool OPENED. Doing this guaranteed the bot to execute my scripts during event perfectly. Now moving onto the slime, I'm trying to use trick but with other steps.

1) Let both accounts setup everything in coop room. Meaning skills, party and mission setup are all ready (except for Master account not clicking on Ready obviously)
2) Leave the DevTool open, refresh the page on each account.
3) Close laptop lid and reopen, login Microsoft account again. 
4) Sometimes I get network error change and reloading page again can be longer.
5) Open bot. 
6) Activate Master account plugin first. Then Slave account plugin. Devtool windows MUST BE OPEN before. Failing to leave devtool open before will cause the issue bot reloading and not executing commands.
7) NO RELOADING on Slave page. Doing this also almost guaranteed to cause the same bug again.

This is how it works for me. Step 1-5 is probably just placebo effect in some cases, but step 5-7 guaranteed to make my bot work with slime coop about 9/10. I've been using this trick for past few days without much problem. When bot doesn't execute command I just repeat step 5-7 instead of repeating 1-4.

-

**Comment by spongebear** [comment] 2017-06-13 04:49
No issue after the update. However if i set use viramate on it goes all buggy. Are u sliming with it on? Off is working fine though.

**Comment by i-Grey** [comment] 2017-06-13 08:15
Thank you @MagCat for enlighten!!

I think the correction method is just "Activate Master account plugin first. Then Slave account plugin. Devtool windows MUST BE OPEN before. Failing to leave devtool open before will cause the issue bot reloading and not executing commands."

This's confirm because if I activate the slave account first, the player ID appear in console will be the same one. (only slave gbf ID appear in the console). but after I active master account first, the GBF ID appear on the console is correctly.

**Comment by Masuzu** [comment] 2017-06-25 20:18
Sorry about necro.
About Viramate, please make sure to turn on this option:
![](https://i.imgur.com/qtDDuG0.png)
Below is an example of how fast it can go with Viramate:
https://www.youtube.com/watch?v=PNAfeDmIEkI

**Closed by Masuzu** 2017-06-25 20:18 UTC
