### ISSUE TITLE
Crash in co-op mode with v1.14.3 at the start of the turn

### ISSUE THREAD

**Issue by Dreamfinal** [Masuzu/ZooeyBot#192] opened 2017-08-11 07:58 UTC
After updating system MaxTriggerDelayInMsBeforeFallback

Time to run the bot in coop mode, it is strange behavior.

1. ID Main press Ready
2. ID Secondary press start (secondary ID is Host Creep room)
3.ID Secondary Loading
4.ID Main Loading
5. Secondary load is completed. Instead, it will attack. It refreshes itself.
Because it enters conditions. MaxTriggerDelayInMsBeforeFallback = 7000
It waits for more than 7 seconds. So I refresh myself.
6. Main load ID completed. But wait for the secondary id. Because setbots are always attacked before the main attack.
7. Secondary Load Complete , Start Attack
8. ID Main Attack ID
9. The enemy died, loops started.

Step 5 makes Farming slow down Because it should not refresh itself. It should load and then attack.

I edited it by setting. MaxTriggerDelayInMsBeforeFallback = 14000

The result is a problem has gone. The bot is back to work normally. As it should be (Not refreshed again)

But it is a serious new problem. When you open the bots for 10-15 minutes.

The bot will have to stop at all. (bot has stop working)

This problem I'm trying to find a cause for a big break.

Notice
- The bot will have a stop in step 5 (it has stopped, but no attack is started). Until I had to attack myself. Then start the new bot from scratch.
- I try to set MaxTriggerDelayInMsBeforeFallback to 9000 11000 70000, it still Has stop anyway.
- I try to set less than 7000 (set to 3500), the result is that the bubbles will reflow itself. Slower
So I have to solve the problem is to set the original 7000 times. Allow it to refreshing itself. Slow down the farm but no stopping is better (better open the bot. Sleep and wake up Stop, then nothing at all)

I noticed in Youtube you take the load in front of the fight just 4 seconds.
The part I took to load in front of the fight was 11 seconds.

Think about the function. MaxTriggerDelayInMsBeforeFallback Here is the problem.

Want to help you check it. Thank you

sorry my Interpreter does not exist
i google translate

**Comment by Masuzu** [comment] 2017-08-11 17:46
Hi,

Could you set `DoNotWaitForServerResponse` to `false` instead of `true` and `MinWaitTimeInMsAfterAbility` to say 2 seconds for instance (2500 for instance).
Regardless of this issue, I am aware of a crash issue with the version 1.14.3 occurring at the very beginning of a turn. I found where the bug was but I am not exactly sure why it happens.

**Comment by Masuzu** [comment] 2017-08-11 17:53
Please make sure that you also took into account this remark:
https://github.com/Masuzu/ZooeyBot/wiki/Slave-mode-(slime-basting)#other-important-remarks

**Comment by Masuzu** [comment] 2017-08-11 17:58
[ZooeyBot.zip](https://github.com/Masuzu/ZooeyBot/files/1218690/ZooeyBot.zip)

Please replace your ZooeyBot.exe with the one enclosed.
This version should not crash at all.
After running it for a while, you may have a file named `debug.txt` in the same folder as the executable file.
I would appreciate greatly if you could send me its contents.

**Comment by Dreamfinal** [comment] 2017-08-11 18:27
I noticed that

The bot will have a stop.

If the first page to load the page before the main battle.

(I set ProcessMainAccountTurnFirst=false)

**Comment by Dreamfinal** [comment] 2017-08-11 18:30
1.ID Main press Ready
2.ID Secondary press start (secondary ID is Host Creep room)
3.ID Secondary Loading
4.ID Main Loading
5.ID Secondary Loading complete and Use Skill 1
6.ID Main  Loading complete and Use Skill 1
7.go to loop step 1


but

1.ID Main press Ready
2.ID Secondary press start (secondary ID is Host Creep room)
3.ID Secondary Loading
4.ID Main Loading
5.ID Main  Loading complete and wait <<<<<< 
6.ID Secondary Loading complete not use skill <<<<<< 
7.bot has stop working

**Comment by Dreamfinal** [comment] 2017-08-11 18:34
Okay, I'll try ZooeyBot.zip

Then hurry to report.

**Comment by Dreamfinal** [comment] 2017-08-11 18:39
Do you have a personal email? I will vdo and send it to you.

**Comment by Jagger0083** [comment] 2017-08-11 22:51
I'm having the exact same issue and tried to do what you said to to remedy it however I still get a problem. here's the debug text from mine.

[debug.txt](https://github.com/Masuzu/ZooeyBot/files/1219256/debug.txt)

**Comment by Dreamfinal** [comment] 2017-08-12 06:13
When i got to try
Use the .exe that you provided.

The bot does not refresh anymore. (step5)

Now I do not need to fix this (MaxTriggerDelayInMsBeforeFallback)

------------

But I try to fix it. MaxTriggerDelayInMsBeforeFallback = 14000
Willfully causes an error.
To find this error for you.
The result is that bots do not crash anymore.


thank you very much

**Comment by Dreamfinal** [comment] 2017-08-12 12:34
I've edited and updated my recent report. Please read the message above. Thank you very much.

**Comment by Dreamfinal** [comment] 2017-08-13 12:44
Hi guys!

It seems I could identify some problems. 

After I got your .exe yesterday, I tested it on the pc for 10 hours and no errors or “has stop”appeared.
However, I forgot to tell you that the time I encountered bugs was when I ran it on Mac Book Air (I bought both of your licenses)

Today I try coop mode on both PC and Mac Book Air. The result is the bot goes wrong on Mac Book Air. It refreshes itself once because ready screen doesn’t load to battle screen within 7 seconds.

So I change the time to 14 seconds and the bot doesn’t refresh anymore.

On the other hand, the bot stops working after using it with your.exe for 10-15 minutes.

Therefore, I send this issue to help you get closer to the problems.
1.	I downloaded your bot again.
2.	I didn’t change any value except 14 seconds and set coop mode to True. All other is set as default.

As you’ve updated new version .4
I downloaded the new one and tried on PC with default setting. The result is that the bot had stop working, this rarely occurs like every 2-3 hours per time.

To solve this problem, I use the previous version .3 that contains your .exe and everything works very fine and back to normal.

This is my 2 environments spec:
PC
Fx8350
RAM 16 GB

Mac Book Air 2016
i5
RAM 16 GB


Thank you very much for your effort and dedication to improve the bot.

**Comment by Masuzu** [comment] 2017-08-13 13:00
Hi,

Thank you for sending the contents of the debug.txt file.
I see what the problem is now and will try to provide a fix similar to the one in the version 1.14.4pre above.

**Comment by Masuzu** [comment] 2017-08-13 13:50
@Jagger0083 @Dreamfinal The crash issue has just been fixed in the newly released version 1.14.5, which tackles this particular issue.

**Comment by Dreamfinal** [comment] 2017-08-14 08:49
For the new patch 1.14.5 that you provided, there's still bug 'has stop working' and I couldn't leave the screen because it could happen any time.

**Comment by Masuzu** [comment] 2017-08-14 22:18
Ah damn it, hmm I guess I'll add some very silly messages in the console and a brute force workaround for it...
So something similar to the version 1.14.4pre would be OK I guess?

**Comment by Masuzu** [comment] 2017-08-14 22:30
The version 1.14.6 has just been released.
If it crashes, you should see letters appearing in the console messages (a, b, c and so on).
If it does not crashes, then you may sometimes have in the same folder as ZooeyBot.exe a file named debug.txt
This issue is actually computer dependent: I faced it on a less powerful laptop but can't reproduce it on my desktop computer. In any case, I am afraid I won't have the time to dig into it further since the magna fest ends in a few hours from now :(
However, I am quite confident that you should have more success with version 1.14.6 which is very close to the version 1.14.4pre which you tried earlier and worked OK on your side.

**Closed** 2017-08-16 09:16 UTC
